# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thiagolc3/APS/blob/master/Untitled15.ipynb
"""

# Band Name Generator Project

print("Welcome to the Band Name Generator.")
city = input("Which city did you grow up in?\n")
pet = input("What is the name of a pet?\n")
print("Your Band could be: " + city + " " + pet)